import type { Logger } from '../logging/logger.js';
import { getBytes, getJson, postJson } from '../util/http.js';
import { sniffImageMime } from '../util/files.js';
import type {
  Gateway,
  GatewayCapabilities,
  ImageGenParams,
  ImageGenResult,
  ListModelsResult,
  ModelInfo,
} from './types.js';

const BASE = 'https://api.mistral.ai/v1';

interface MistralModel {
  id: string;
  created?: number;
  aliases?: string[];
  capabilities?: { completion_chat?: boolean; function_calling?: boolean; vision?: boolean };
}

/**
 * Mistral image generation runs through the Agents API `image_generation` tool
 * (backed by FLUX1.1 [pro] Ultra). There is no standalone image endpoint and no
 * structured size/aspect/count parameters — we steer composition via the prompt.
 *
 * The "model" selected in config is the orchestrator LLM that drives the agent.
 */
export class MistralGateway implements Gateway {
  readonly id = 'mistral' as const;
  readonly capabilities: GatewayCapabilities = {
    imageGeneration: true,
    textToVideo: false,
    imageToVideo: false,
    imageAspectRatioParam: false,
    imageResolutionParam: false,
    listsImageModels: true,
    listsVideoModels: false,
    multiReferenceImages: false,
    imageReferenceImages: false,
  };

  /** Cache of orchestrator-model -> created agent id (per process). */
  private agentCache = new Map<string, string>();

  constructor(
    private readonly token: string,
    private readonly logger: Logger,
  ) {}

  private headers(): Record<string, string> {
    return { Authorization: `Bearer ${this.token}` };
  }

  imageAspectRatios(): null {
    return null; // not a real param — wizard falls back to the curated list, encoded into the prompt
  }
  imageResolutions(): null {
    return null;
  }

  async listImageModels(signal?: AbortSignal): Promise<ListModelsResult> {
    const data = await getJson<{ data: MistralModel[] }>(`${BASE}/models`, { headers: this.headers(), signal });
    const seen = new Set<string>();
    const models = (data.data ?? [])
      .filter((m) => m.capabilities?.completion_chat && m.capabilities?.function_calling)
      .map<ModelInfo>((m) => ({
        id: m.aliases?.find((a) => a.endsWith('-latest')) ?? m.id,
        name: m.id,
        ...(m.created !== undefined ? { created: m.created } : {}),
        raw: m,
      }))
      .filter((m) => {
        if (seen.has(m.id)) return false;
        seen.add(m.id);
        return true;
      })
      .sort((a, b) => (b.created ?? 0) - (a.created ?? 0));
    return {
      models,
      source: 'api',
      warnings: [],
      notes: ['Mistral images are generated by FLUX1.1 [pro] Ultra via the Agents tool; the model you pick here is the orchestrator LLM.'],
    };
  }

  // Sampling args (temperature/top_p) live on the AGENT, not the conversation — the
  // conversation endpoint rejects completion_args when an agent_id is set. So cache one
  // agent per (orchestrator + sampling args) combination.
  private async ensureAgent(orchestratorModel: string, completionArgs: Record<string, unknown>, signal?: AbortSignal): Promise<string> {
    const key = `${orchestratorModel}|${JSON.stringify(completionArgs)}`;
    const cached = this.agentCache.get(key);
    if (cached) return cached;
    const agent = await postJson<{ id: string }>(
      `${BASE}/agents`,
      {
        model: orchestratorModel,
        name: 'ai-image-router-mcp image agent',
        description: 'Generates images via the image_generation tool.',
        instructions: 'Always use the image generation tool to create the requested image. Do not ask clarifying questions.',
        tools: [{ type: 'image_generation' }],
        ...(Object.keys(completionArgs).length > 0 ? { completion_args: completionArgs } : {}),
      },
      // Creating an agent bills nothing — a duplicate from a retried POST is harmless.
      { headers: this.headers(), signal, idempotent: true },
    );
    if (!agent.id) throw new Error('Mistral did not return an agent id.');
    this.agentCache.set(key, agent.id);
    this.logger.info('Created Mistral image agent', { orchestrator: orchestratorModel, agentId: agent.id, completionArgs });
    return agent.id;
  }

  async generateImage(params: ImageGenParams): Promise<ImageGenResult> {
    const orchestrator = params.model || 'mistral-medium-latest';
    const agentId = await this.ensureAgent(orchestrator, completionArgsFor(params), params.signal);
    params.onProgress?.('submitted');
    const prompt = promptWithSteering(params);

    const convo = await postJson<MistralConversation>(
      `${BASE}/conversations`,
      { inputs: prompt, agent_id: agentId, stream: false },
      { headers: this.headers(), signal: params.signal, timeoutMs: 180_000 },
    );

    const { fileIds, text } = extractToolFiles(convo);
    if (fileIds.length === 0) {
      throw new Error(`Mistral returned no image file. Assistant said: ${truncate(text ?? '(none)', 300)}`);
    }

    const images = [];
    for (const fileId of fileIds) {
      const bytes = await getBytes(`${BASE}/files/${fileId}/content`, {
        headers: { ...this.headers(), Accept: 'application/octet-stream' },
        signal: params.signal,
        timeoutMs: 120_000,
      });
      images.push({ bytes, mimeType: sniffImageMime(bytes) });
    }

    const warnings = ignoredParamWarnings(params);
    return {
      images,
      ...(text ? { text } : {}),
      ...(warnings.length > 0 ? { warnings } : {}),
      modelUsed: `${orchestrator} + image_generation (FLUX1.1 [pro] Ultra)`,
      raw: convo,
    };
  }
}

/** The agents image tool takes a prompt only — say which caller fields had no effect. */
function ignoredParamWarnings(params: ImageGenParams): string[] {
  const extra = params.extra ? Object.keys(params.extra) : [];
  return extra.length > 0
    ? [`provider_options (${extra.join(', ')}) were ignored: Mistral's image_generation tool takes no request fields besides the prompt.`]
    : [];
}

export interface MistralConversation {
  outputs?: Array<{
    type?: string;
    content?: Array<{ type?: string; text?: string; file_id?: string; tool?: string }>;
  }>;
}

/** Sampling args live on the AGENT (the conversation endpoint 422s on them when `agent_id` is set). */
function completionArgsFor(params: ImageGenParams): Record<string, unknown> {
  return {
    ...(params.temperature != null ? { temperature: params.temperature } : {}),
    ...(params.topP != null ? { top_p: params.topP } : {}),
  };
}

/** Mistral has no size/aspect params — steer through the prompt. */
function promptWithSteering(params: ImageGenParams): string {
  let prompt = params.prompt;
  if (params.aspectRatio) prompt += `\n\n(Compose the image in a ${params.aspectRatio} aspect ratio.)`;
  if (params.negativePrompt) prompt += `\n\n(Avoid: ${params.negativePrompt}.)`;
  return prompt;
}

type MistralContentItem = NonNullable<NonNullable<MistralConversation['outputs']>[number]['content']>[number];

/**
 * The generated files referenced by the conversation. The same `tool_file` can be referenced
 * more than once (seen live: one render reported as "2 images", byte-identical, downloaded and
 * Tinify-compressed twice), so ids are de-duplicated.
 */
export function extractToolFiles(convo: MistralConversation): { fileIds: string[]; text?: string } {
  const items: MistralContentItem[] = (convo.outputs ?? []).flatMap((o) => (Array.isArray(o.content) ? o.content : []));
  const fileIds = [...new Set(items.filter((i) => i.type === 'tool_file' && i.file_id).map((i) => i.file_id as string))];
  const texts = items.filter((i) => i.type === 'text' && i.text).map((i) => i.text as string);
  return { fileIds, ...(texts.length > 0 ? { text: texts.join(' ') } : {}) };
}

function truncate(s: string, n: number): string {
  return s.length > n ? s.slice(0, n) + '…' : s;
}
