import { existsSync } from 'node:fs';
import { readFile, writeFile } from 'node:fs/promises';
import { z } from 'zod';
import { CONFIG_PATH, resolvePath } from './paths.js';

export const GATEWAYS = ['openrouter', 'mistral', 'edenai', 'fal'] as const;
export type GatewayId = (typeof GATEWAYS)[number];

export const GATEWAY_LABELS: Record<GatewayId, string> = {
  openrouter: 'OpenRouter',
  mistral: 'Mistral AI',
  edenai: 'Eden AI',
  fal: 'fal.ai',
};

/** Default project-root token files (token text only, no prefix). */
export const DEFAULT_TOKEN_FILES: Record<GatewayId, string> = {
  openrouter: 'openrouter token.txt',
  mistral: 'mistral ai token.txt',
  edenai: 'eden ai token.txt',
  fal: 'fal ai token.txt',
};

/** Default project-root file holding the Tinify (TinyPNG) API key. */
export const TINIFY_TOKEN_FILE = 'tinify com token.txt';

/** Default project-root file holding the HTTP transport's bearer token (generated by the wizard). */
export const HTTP_AUTH_TOKEN_FILE = 'mcp http token.txt';

export class ConfigError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'ConfigError';
  }
}

const tokenSourceSchema = z.object({
  type: z.enum(['file', 'inline', 'env']),
  value: z.string(),
});
export type TokenSource = z.infer<typeof tokenSourceSchema>;

const imageObject = z.object({
  model: z.string().nullable().default(null),
  /** Eden AI sub-provider slug (e.g. "openai", "stabilityai"); null for other gateways. */
  edenProvider: z.string().nullable().default(null),
  defaultAspectRatio: z.string().nullable().default(null),
  defaultResolution: z.string().nullable().default(null),
  supportedAspectRatios: z.array(z.string()).nullable().default(null),
  supportedResolutions: z.array(z.string()).nullable().default(null),
  /** Run generation as an async background job (submit → poll by `job_id`) by default. */
  async: z.boolean().default(true),
});

const videoObject = z.object({
  enabled: z.boolean().default(false),
  model: z.string().nullable().default(null),
  edenProvider: z.string().nullable().default(null),
  defaultResolution: z.string().nullable().default(null),
  defaultFps: z.number().nullable().default(null),
  defaultDuration: z.number().nullable().default(null),
  /** Run generation as an async background job (submit → poll by `job_id`) by default. */
  async: z.boolean().default(true),
});

const i2vObject = videoObject.extend({
  /** Whether the selected model accepts multiple reference images. */
  multiReference: z.boolean().default(false),
});

const diagnosticsObject = z.object({
  configuredAt: z.string().default(''),
  wizardVersion: z.string().default(''),
  /** Errors / missing entries encountered while the wizard pulled data from APIs. */
  issues: z
    .array(
      z.object({
        severity: z.enum(['error', 'warning']),
        area: z.string(),
        message: z.string(),
      }),
    )
    .default([]),
  /** Per-tool record of where the model/option list came from. */
  sources: z
    .record(
      z.string(),
      z.object({
        listed: z.boolean(),
        source: z.enum(['api', 'fallback', 'manual']),
        count: z.number(),
      }),
    )
    .default({}),
});
export type Diagnostics = z.infer<typeof diagnosticsObject>;

export const configSchema = z.object({
  version: z.number().default(1),
  gateway: z.enum(GATEWAYS),
  token: tokenSourceSchema,
  /** Orchestrator LLM used to drive Mistral's image_generation agent tool. */
  mistralAgentModel: z.string().default('mistral-medium-latest'),
  output: z
    .object({
      dir: z.string().default('output'),
      inlinePreview: z.boolean().default(true),
      previewMaxBytes: z.number().default(1_500_000),
    })
    .default({}),
  logging: z
    .object({
      policy: z.enum(['none', 'today', 'persistent-daily']).default('today'),
      dir: z.string().default('logs'),
    })
    .default({}),
  http: z
    .object({
      enabled: z.boolean().default(false),
      host: z.string().default('127.0.0.1'),
      port: z.number().default(8765),
      /**
       * Optional shared secret for the HTTP transport. When set, every /mcp request must carry
       * `Authorization: Bearer <token>` (or `X-API-Key: <token>`). Required in practice when the
       * port is exposed publicly (e.g. a tunnel for a Le Chat connector) — tools read local paths.
       */
      authToken: tokenSourceSchema.nullable().default(null),
      /**
       * Extra hostnames (no port) accepted in the `Host`/`Origin` headers while NO authToken is
       * set. Loopback names and IP literals are always accepted; any other name is refused —
       * that is the DNS-rebinding guard (a rebinding page always carries its own domain). Not
       * consulted when an authToken is set (the token is then the protection).
       */
      allowedHosts: z.array(z.string().min(1)).default([]),
      /** Close an HTTP session after this long without a request (an open SSE stream keeps it alive). */
      sessionIdleMinutes: z.number().int().min(1).default(30),
    })
    .default({}),
  image: imageObject.default({}),
  imageToVideo: i2vObject.default({}),
  textToVideo: videoObject.default({}),
  backgroundRemoval: z
    .object({
      model: z.enum(['none', 'birefnet-general', 'birefnet-massive', 'bria-rmbg', 'isnet-general-use', 'ben2-base']).default('birefnet-general'),
      executionProvider: z.enum(['auto', 'dml', 'cuda', 'coreml', 'cpu', 'webgpu']).default('auto'),
      modelsDir: z.string().default('models'),
    })
    .default({}),
  /** Optional Tinify (TinyPNG) key — when set, generate_image can compress PNGs and output WebP. */
  tinify: z.object({ token: tokenSourceSchema }).nullable().default(null),
  diagnostics: diagnosticsObject.default({}),
});

export type AppConfig = z.infer<typeof configSchema>;
export type ImageConfig = AppConfig['image'];
export type VideoConfig = AppConfig['textToVideo'];
export type ImageToVideoConfig = AppConfig['imageToVideo'];
export type BackgroundRemovalConfig = AppConfig['backgroundRemoval'];
export type BackgroundRemovalModel = BackgroundRemovalConfig['model'];
export type ExecutionProviderSetting = BackgroundRemovalConfig['executionProvider'];

export async function loadConfig(path: string = CONFIG_PATH): Promise<AppConfig> {
  if (!existsSync(path)) {
    throw new ConfigError(`No configuration found at ${path}. Run \`npm run configure\` first.`);
  }
  let raw: unknown;
  try {
    raw = JSON.parse(await readFile(path, 'utf8'));
  } catch (err) {
    throw new ConfigError(`Could not parse config at ${path}: ${(err as Error).message}`);
  }
  const parsed = configSchema.safeParse(raw);
  if (!parsed.success) {
    throw new ConfigError(`Invalid config at ${path}: ${parsed.error.issues.map((i) => `${i.path.join('.')}: ${i.message}`).join('; ')}`);
  }
  return parsed.data;
}

export async function saveConfig(cfg: AppConfig, path: string = CONFIG_PATH): Promise<void> {
  const parsed = configSchema.parse(cfg);
  await writeFile(path, JSON.stringify(parsed, null, 2) + '\n', 'utf8');
}

/**
 * Resolve the actual secret token from its configured source. Every source fails
 * on an empty/whitespace-only value — an empty secret must never reach a caller,
 * where it could be read as "not configured" (e.g. HTTP auth silently disabled).
 */
export async function resolveToken(src: TokenSource): Promise<string> {
  if (src.type === 'inline') {
    const v = src.value.trim();
    if (!v) throw new ConfigError('Inline token is empty.');
    return v;
  }
  if (src.type === 'env') {
    const raw = process.env[src.value];
    if (raw === undefined) throw new ConfigError(`Environment variable ${src.value} is not set (token source).`);
    const v = raw.trim();
    if (!v) throw new ConfigError(`Environment variable ${src.value} is empty (token source).`);
    return v;
  }
  const p = resolvePath(src.value);
  if (!existsSync(p)) throw new ConfigError(`Token file not found: ${p}`);
  const txt = (await readFile(p, 'utf8')).trim();
  if (!txt) throw new ConfigError(`Token file is empty: ${p}`);
  return txt;
}
